import jax.numpy as jnp
from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.utils import conversion as conversion, math as math
from typing import Any

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Bernoulli(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(
        self,
        logits: Numeric | None = None,
        probs: Numeric | None = None,
        dtype: jnp.dtype | type[Any] = ...,
    ) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    @property
    def logits(self) -> Array: ...
    @property
    def probs(self) -> Array: ...
    def log_prob(self, value: EventT) -> Array: ...
    def prob(self, value: EventT) -> Array: ...
    def cdf(self, value: EventT) -> Array: ...
    def log_cdf(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mean(self) -> Array: ...
    def variance(self) -> Array: ...
    def mode(self) -> Array: ...
    def __getitem__(self, index) -> Bernoulli: ...
