import jax.numpy as jnp
from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.utils import math as math
from typing import Any

tfd: Incomplete
Array: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Categorical(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(
        self,
        logits: Array | None = None,
        probs: Array | None = None,
        dtype: jnp.dtype | type[Any] = ...,
    ) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def logits(self) -> Array: ...
    @property
    def probs(self) -> Array: ...
    @property
    def num_categories(self) -> int: ...
    def log_prob(self, value: EventT) -> Array: ...
    def prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mode(self) -> Array: ...
    def cdf(self, value: EventT) -> Array: ...
    def log_cdf(self, value: EventT) -> Array: ...
    def logits_parameter(self) -> Array: ...
    def __getitem__(self, index) -> Categorical: ...

CategoricalLike: Incomplete
