from absl.testing import parameterized
from distrax._src.distributions import categorical_uniform as categorical_uniform

class CategoricalUniformTest(parameterized.TestCase):
    def test_raises_on_wrong_logits(self) -> None: ...
    def test_batch_shape(
        self, *, low, high, logits, target_batch_shape, **_
    ) -> None: ...
    def test_event_shape(
        self, *, low, high, logits, target_event_shape, **_
    ) -> None: ...
    def test_sample_shape(
        self, *, low, high, logits, target_sample_shape, **_
    ) -> None: ...
    def test_sample_gradients(self, *, low, high, logits, **_): ...
    def test_entropy(self, *, low, high, logits, target_entropy, **_) -> None: ...
    def test_mean(self, *, low, high, logits, target_mean, **_) -> None: ...
    def test_variance(self, *, low, high, logits, target_variance, **_) -> None: ...
    def test_log_prob(self, *, low, high, logits, target_sample_shape, **_) -> None: ...
    def test_attributes(
        self, *, low, high, logits, target_low, target_high, target_logits, **_
    ) -> None: ...
    def test_slice(self, low, high, logits, **_) -> None: ...
    def test_log_prob_outside_of_domain(
        self, *, low, high, logits, target_sample_shape, **_
    ) -> None: ...
    def test_vmap_inputs(self, *, low, high, logits, target_sample_shape, **_): ...
    def test_vmap_outputs(self, *, low, high, logits, target_sample_shape, **_): ...
    def test_jitable(self): ...
