from absl.testing import parameterized
from distrax._src.distributions import (
    clipped as clipped,
    logistic as logistic,
    normal as normal,
)

MINIMUM: float
MAXIMUM: float
LOC = MINIMUM
SCALE: float
SIZE: int

class ClippedTest(parameterized.TestCase):
    def test_clipped_logprob(self, factory, unclipped_factory) -> None: ...
    def test_batched_clipped_logprob(self, factory, unclipped_factory) -> None: ...
    def test_clipped_sampled_and_logprob(self, factory, unclipped_factory) -> None: ...
    def test_clipped_sample(self, factory, unclipped_factory) -> None: ...
    def test_extremes(self, factory) -> None: ...
    def test_jitable(self): ...
    def test_properties(self) -> None: ...
    def test_min_max_broadcasting(self) -> None: ...
    def test_batch_shape(self) -> None: ...
    def test_event_shape(self) -> None: ...
