from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Deterministic(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(
        self, loc: Numeric, atol: Numeric | None = None, rtol: Numeric | None = None
    ) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    @property
    def loc(self) -> Array: ...
    @property
    def atol(self) -> Array: ...
    @property
    def rtol(self) -> Array: ...
    @property
    def slack(self) -> Array: ...
    def log_prob(self, value: EventT) -> Array: ...
    def prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mean(self) -> Array: ...
    def mode(self) -> Array: ...
    def variance(self) -> Array: ...
    def stddev(self) -> Array: ...
    def log_cdf(self, value: EventT) -> Array: ...
    def cdf(self, value: EventT) -> Array: ...
    def __getitem__(self, index) -> Deterministic: ...
