from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.distributions.beta import Beta as Beta
from distrax._src.utils import conversion as conversion, math as math

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Dirichlet(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(self, concentration: Array) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    @property
    def concentration(self) -> Array: ...
    def log_prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mean(self) -> Array: ...
    def mode(self) -> Array: ...
    def variance(self) -> Array: ...
    def covariance(self) -> Array: ...
    def __getitem__(self, index) -> Dirichlet: ...

DirichletLike: Incomplete
