from _typeshed import Incomplete
from distrax._src.distributions import epsilon_greedy as epsilon_greedy
from distrax._src.utils import equivalence as equivalence

class EpsilonGreedyTest(equivalence.EquivalenceTest):
    epsilon: float
    preferences: Incomplete
    def setUp(self) -> None: ...
    def test_parameters_from_preferences(self) -> None: ...
    def test_num_categories(self) -> None: ...
    def test_sample_dtype(self, dtype) -> None: ...
    def test_jittable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_ellipsis(self) -> None: ...
