from distrax._src.distributions import gamma as gamma
from distrax._src.utils import equivalence as equivalence

class GammaTest(equivalence.EquivalenceTest):
    def setUp(self) -> None: ...
    def test_properties(self, concentration_shape, rate_shape, batch_shape) -> None: ...
    def test_sample_shape(self, distr_params, sample_shape) -> None: ...
    def test_sample_dtype(self, dtype) -> None: ...
    def test_sample_and_log_prob(self, distr_params, sample_shape) -> None: ...
    def test_method_with_value(self, distr_params, value) -> None: ...
    def test_method(self, distr_params) -> None: ...
    def test_with_two_distributions(self, function_string, mode_string): ...
    def test_jitable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
