from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.utils import conversion as conversion

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Gamma(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(self, concentration: Numeric, rate: Numeric) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    @property
    def concentration(self) -> Array: ...
    @property
    def rate(self) -> Array: ...
    def log_prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def cdf(self, value: EventT) -> Array: ...
    def log_cdf(self, value: EventT) -> Array: ...
    def mean(self) -> Array: ...
    def stddev(self) -> Array: ...
    def variance(self) -> Array: ...
    def mode(self) -> Array: ...
    def __getitem__(self, index) -> Gamma: ...
