from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.distributions import normal as normal

kl_module: Incomplete

class LogStddevNormalTest(parameterized.TestCase):
    def test_log_scale_property(self, mean, log_stddev, expected) -> None: ...
    def test_sampling_scalar(self, mean, stddev) -> None: ...
    def test_sampling_vector(self, mean, stddev) -> None: ...
    def test_sampling_batched(self) -> None: ...
    def test_sampling_batched_custom_dim(self) -> None: ...
    def test_sample_dtype(self, dtype) -> None: ...
    def test_kl_versus_normal(self) -> None: ...
    def test_custom_kl_registered(self) -> None: ...
    def test_calling_custom_kl(self) -> None: ...
    def test_jitable(self): ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
