from distrax._src.distributions import logistic as logistic
from distrax._src.utils import equivalence as equivalence

class Logistic(equivalence.EquivalenceTest):
    def setUp(self) -> None: ...
    def test_event_shape(self, distr_params) -> None: ...
    def test_sample_shape(self, distr_params, sample_shape) -> None: ...
    def test_sample_dtype(self, dtype) -> None: ...
    def test_sample_and_log_prob(self, distr_params, sample_shape) -> None: ...
    def test_method_with_input(self, distr_params, value) -> None: ...
    def test_method(self, distr_params, function_string) -> None: ...
    def test_median(self, distr_params) -> None: ...
    def test_jitable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
