from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.distributions.categorical import Categorical as Categorical
from distrax._src.distributions.mixture_same_family import (
    MixtureSameFamily as MixtureSameFamily,
)
from distrax._src.distributions.mvn_diag import (
    MultivariateNormalDiag as MultivariateNormalDiag,
)
from distrax._src.distributions.normal import Normal as Normal
from distrax._src.utils import equivalence as equivalence

tfd: Incomplete

class TFPLogitsCategoricalTFPMultivariateComponents(equivalence.EquivalenceTest):
    batch_shape: Incomplete
    num_components: int
    mixture_dist: Incomplete
    tfp_mixture_dist: Incomplete
    components_dist: Incomplete
    tfp_components_dist: Incomplete
    def setUp(self) -> None: ...
    def test_event_shape(self) -> None: ...
    def test_batch_shape(self) -> None: ...
    def test_invalid_parameters(self) -> None: ...
    def test_sample_shape(self, sample_shape) -> None: ...
    def test_sample_dtype(self) -> None: ...
    def test_sample_and_log_prob(self, sample_shape) -> None: ...
    def test_method(self, function_string) -> None: ...
    def test_jittable(self) -> None: ...

class TFPLogitsCategoricalTFPUnivariateComponents(
    TFPLogitsCategoricalTFPMultivariateComponents
): ...
class TFPProbsCategoricalTFPMultivariateComponents(
    TFPLogitsCategoricalTFPMultivariateComponents
): ...
class DistraxLogitsCategoricalTFPMultivariateComponents(
    TFPLogitsCategoricalTFPMultivariateComponents
): ...
class DistraxProbsCategoricalTFPMultivariateComponents(
    TFPLogitsCategoricalTFPMultivariateComponents
): ...
class DistraxLogitsCategoricalTFPUnivariateComponents(
    TFPLogitsCategoricalTFPUnivariateComponents
): ...
class DistraxLogitsCategoricalDistraxMultivariateComponents(
    DistraxLogitsCategoricalTFPMultivariateComponents
): ...
class DistraxLogitsCategoricalDistraxUnivariateComponents(
    DistraxLogitsCategoricalTFPUnivariateComponents
): ...
class TFPLogitsCategoricalDistraxMultivariateComponents(
    TFPLogitsCategoricalTFPMultivariateComponents
): ...
class TFPLogitsCategoricalDistraxUnivariateComponents(
    TFPLogitsCategoricalTFPUnivariateComponents
): ...

class MixtureSameFamilySlicingTest(parameterized.TestCase):
    loc: Incomplete
    scale_diag: Incomplete
    components_dist: Incomplete
    logits: Incomplete
    mixture_dist: Incomplete
    dist: Incomplete
    def setUp(self) -> None: ...
    def assertion_fn(self, rtol): ...
    def test_slice(self, slice_, expected_batch_shape) -> None: ...
    def test_slice_ellipsis(self) -> None: ...
