from _typeshed import Incomplete
from distrax._src.distributions import mixture_of_two as mixture_of_two
from distrax._src.utils import equivalence as equivalence

BATCH_SIZE: int
PROPORTION: float

class MixtureOfTwoTest(equivalence.EquivalenceTest):
    component_a: Incomplete
    component_b: Incomplete
    tfp_mixture: Incomplete
    def setUp(self) -> None: ...
    def assertion_fn(self, rtol: float = 0.001): ...
    def test_mixture_methods(self) -> None: ...
    def test_sample_and_log_prob(self, sample_shape) -> None: ...
    def test_jitable(self): ...
    def test_prob_a(self) -> None: ...
    def test_prob_b(self) -> None: ...
    def test_batch_shape(self) -> None: ...
    def test_event_shape(self) -> None: ...
    def test_slice(self, slice_, expected_batch_shape) -> None: ...
    def test_invalid_parameters(self) -> None: ...
