import jax.numpy as jnp
from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.utils import conversion as conversion, math as math
from typing import Any

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Multinomial(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(
        self,
        total_count: Numeric,
        logits: Array | None = None,
        probs: Array | None = None,
        dtype: jnp.dtype | type[Any] = ...,
    ) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    @property
    def total_count(self) -> Array: ...
    @property
    def num_trials(self) -> Array: ...
    @property
    def logits(self) -> Array: ...
    @property
    def probs(self) -> Array: ...
    @property
    def log_of_probs(self) -> Array: ...
    def log_prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mean(self) -> Array: ...
    def variance(self) -> Array: ...
    def covariance(self) -> Array: ...
    def __getitem__(self, index) -> Multinomial: ...
