from distrax._src.distributions import mvn_diag as mvn_diag, normal as normal
from distrax._src.utils import equivalence as equivalence

class MultivariateNormalDiagTest(equivalence.EquivalenceTest):
    def setUp(self) -> None: ...
    def test_event_shape(self, distr_params) -> None: ...
    def test_batch_shape(self, distr_params) -> None: ...
    def test_invalid_parameters(self) -> None: ...
    def test_sample_shape(self, distr_params, sample_shape) -> None: ...
    def test_sample_and_log_prob(self, distr_params, sample_shape) -> None: ...
    def test_sample_dtype(self, dtype) -> None: ...
    def test_pdf(self, function_string, distr_params, value) -> None: ...
    def test_cdf(self, function_string, distr_params, value): ...
    def test_method(self, function_string, distr_params) -> None: ...
    def test_median(self) -> None: ...
    def test_with_two_distributions(self, function_string, mode_string) -> None: ...
    def test_jittable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
    def test_slice_ellipsis(self) -> None: ...
