from distrax._src.distributions import normal as normal
from distrax._src.utils import equivalence as equivalence

class NormalTest(equivalence.EquivalenceTest):
    def setUp(self) -> None: ...
    def test_event_shape(self, distr_params) -> None: ...
    def test_sample_shape(self, distr_params, sample_shape) -> None: ...
    def test_sample_and_log_prob(self, distr_params, sample_shape) -> None: ...
    def test_method_with_input(self, distr_params, value) -> None: ...
    def test_method(self, distr_params, function_string) -> None: ...
    def test_median(self, distr_params) -> None: ...
    def test_with_two_distributions(self, function_string, mode_string) -> None: ...
    def test_jittable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
    def test_vmap_inputs(self): ...
    def test_vmap_outputs(self): ...
