from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.distributions.categorical import Categorical as Categorical
from distrax._src.distributions.independent import Independent as Independent
from distrax._src.distributions.laplace import Laplace as Laplace
from distrax._src.distributions.mvn_diag import (
    MultivariateNormalDiag as MultivariateNormalDiag,
)
from distrax._src.distributions.normal import Normal as Normal
from distrax._src.distributions.tfp_compatible_distribution import (
    tfp_compatible_distribution as tfp_compatible_distribution,
)
from distrax._src.distributions.transformed import Transformed as Transformed
from distrax._src.distributions.uniform import Uniform as Uniform

tfb: Incomplete
tfd: Incomplete

class TFPCompatibleDistributionNormal(parameterized.TestCase):
    base_dist: Incomplete
    values: Incomplete
    distrax_second_dist: Incomplete
    tfp_second_dist: Incomplete
    def setUp(self) -> None: ...
    def assertion_fn(self, rtol): ...
    @property
    def wrapped_dist(self): ...
    def test_event_shape(self) -> None: ...
    def test_event_shape_types(self) -> None: ...
    def test_batch_shape(self) -> None: ...
    def test_sample(self): ...
    def test_experimental_local_measure(self) -> None: ...
    def test_method(self, method) -> None: ...
    def test_method_with_value(self, method) -> None: ...
    def test_with_two_distributions(self, method) -> None: ...

class TFPCompatibleDistributionMvnNormal(TFPCompatibleDistributionNormal):
    base_dist: Incomplete
    values: Incomplete
    distrax_second_dist: Incomplete
    tfp_second_dist: Incomplete
    def setUp(self) -> None: ...

class TFPCompatibleDistributionCategorical(TFPCompatibleDistributionNormal):
    base_dist: Incomplete
    values: Incomplete
    distrax_second_dist: Incomplete
    tfp_second_dist: Incomplete
    def setUp(self) -> None: ...

class TFPCompatibleDistributionTransformed(TFPCompatibleDistributionNormal):
    base_dist: Incomplete
    values: Incomplete
    distrax_second_dist: Incomplete
    tfp_second_dist: Incomplete
    def setUp(self) -> None: ...

class TfpMetaDistributionsWithWrappedBaseDistribution(parameterized.TestCase):
    def setUp(self) -> None: ...
    def assertion_fn(self, rtol): ...
    def test_with_independent(self) -> None: ...
    def test_with_transformed_distribution(self) -> None: ...
    def test_with_sample(self) -> None: ...
    def test_with_joint_distribution_named_auto_batched(self): ...
    def test_with_joint_distribution_coroutine_auto_batched(self) -> None: ...

class TFPCompatibleDistributionSlicing(parameterized.TestCase):
    def assertion_fn(self, rtol): ...
    def test_slice(self, slice_) -> None: ...
