from _typeshed import Incomplete
from distrax._src.distributions import distribution as distribution
from distrax._src.utils import conversion as conversion

tfd: Incomplete
Array: Incomplete
Numeric: Incomplete
PRNGKey: Incomplete
EventT: Incomplete

class Uniform(distribution.Distribution):
    equiv_tfp_cls: Incomplete
    def __init__(self, low: Numeric = 0.0, high: Numeric = 1.0) -> None: ...
    @property
    def event_shape(self) -> tuple[int, ...]: ...
    @property
    def low(self) -> Array: ...
    @property
    def high(self) -> Array: ...
    @property
    def range(self) -> Array: ...
    @property
    def batch_shape(self) -> tuple[int, ...]: ...
    def log_prob(self, value: EventT) -> Array: ...
    def prob(self, value: EventT) -> Array: ...
    def entropy(self) -> Array: ...
    def mean(self) -> Array: ...
    def variance(self) -> Array: ...
    def stddev(self) -> Array: ...
    def median(self) -> Array: ...
    def cdf(self, value: EventT) -> Array: ...
    def log_cdf(self, value: EventT) -> Array: ...
    def __getitem__(self, index) -> Uniform: ...
