from _typeshed import Incomplete
from distrax._src.distributions import von_mises as von_mises
from distrax._src.utils import equivalence as equivalence

class VonMisesTest(equivalence.EquivalenceTest):
    loc: Incomplete
    concentration: Incomplete
    rng: Incomplete
    def setUp(self) -> None: ...
    def test_event_shape(self, distr_params) -> None: ...
    def test_loc_shape_properties(self, shape) -> None: ...
    def test_concentration_shape_properties(self, shape) -> None: ...
    def test_sample_shape(self, distr_params, sample_shape) -> None: ...
    def test_sample_and_log_prob(self, distr_params, sample_shape) -> None: ...
    def test_sample_dtype(self, method, dtype) -> None: ...
    def test_method_with_input(self, distr_params, value) -> None: ...
    def test_method(self, distr_params, function_string) -> None: ...
    def test_with_two_distributions(self, function_string, mode_string) -> None: ...
    def test_jittable(self) -> None: ...
    def test_slice(self, slice_) -> None: ...
    def test_slice_different_parameterization(self) -> None: ...
    def test_von_mises_log_pdf(self) -> None: ...
    def test_von_mises_log_pdf_uniform(self) -> None: ...
    def test_von_mises_pdf(self) -> None: ...
    def test_von_mises_pdf_uniform(self) -> None: ...
    def test_von_mises_cdf(self) -> None: ...
    def test_von_mises_survival_function(self) -> None: ...
    def test_von_mises_cdf_out_of_bounds(self) -> None: ...
    def test_von_mises_log_cdf(self) -> None: ...
    def test_von_mises_log_survival(self) -> None: ...
    def test_von_mises_cdf_uniform(self) -> None: ...
    def test_von_mises_cdf_gradient_simple(self): ...
    def test_von_mises_sample_gradient(self): ...
    def test_von_mises_uniform_sample_gradient(self): ...
    def test_von_mises_sample_gradient_comparison(self, concentration): ...
    def test_von_mises_sample_moments(self) -> None: ...
    def test_von_mises_sample_variance_uniform(self) -> None: ...
    def test_von_mises_sample_extreme_concentration(self) -> None: ...
    def test_von_mises_sample_ks_test(self) -> None: ...
    def test_von_mises_sample_uniform_ks_test(self) -> None: ...
    def test_von_mises_sample_average_gradient(self): ...
    def test_von_mises_sample_circular_variance_gradient(self): ...
