from absl.testing import parameterized
from distrax._src.bijectors import bijector as bijector

class DummyBijector(bijector.Bijector):
    def forward_and_log_det(self, x): ...
    def inverse_and_log_det(self, y): ...

class BijectorTest(parameterized.TestCase):
    def test_invalid_parameters(
        self, ndims_in, ndims_out, cnst_jac, cnst_logdet
    ) -> None: ...
    def test_invalid_inputs(self, method_str) -> None: ...
    def test_jittable(self): ...
