from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.bijectors import scalar_affine as scalar_affine
from distrax._src.utils import conversion as conversion

tfd: Incomplete
tfb: Incomplete
RTOL: float

class BlockTest(parameterized.TestCase):
    seed: Incomplete
    def setUp(self) -> None: ...
    def test_properties(self) -> None: ...
    def test_invalid_properties(self) -> None: ...
    def test_against_tfp_semantics(self, tfp_bijector_fn, ndims) -> None: ...
    def test_forward_inverse_work_as_expected(self, bijector_fn, ndims) -> None: ...
    def test_log_det_jacobian_works_as_expected(self, bijector_fn, ndims) -> None: ...
    def test_raises_on_invalid_input_shape(self): ...
    def test_jittable(self): ...
