from _typeshed import Incomplete
from distrax._src.bijectors import (
    bijector as base,
    chain as chain,
    diag_linear as diag_linear,
    linear as linear,
)

Array: Incomplete

class _IdentityPlusLowRankLinear(base.Bijector):
    def __init__(self, u_matrix: Array, v_matrix: Array) -> None: ...
    def forward(self, x: Array) -> Array: ...
    def forward_log_det_jacobian(self, x: Array) -> Array: ...
    def forward_and_log_det(self, x: Array) -> tuple[Array, Array]: ...
    def inverse(self, y: Array) -> Array: ...
    def inverse_log_det_jacobian(self, y: Array) -> Array: ...
    def inverse_and_log_det(self, y: Array) -> tuple[Array, Array]: ...

class DiagPlusLowRankLinear(linear.Linear):
    forward: Incomplete
    forward_log_det_jacobian: Incomplete
    inverse: Incomplete
    inverse_log_det_jacobian: Incomplete
    inverse_and_log_det: Incomplete
    def __init__(self, diag: Array, u_matrix: Array, v_matrix: Array) -> None: ...
    @property
    def diag(self) -> Array: ...
    @property
    def u_matrix(self) -> Array: ...
    @property
    def v_matrix(self) -> Array: ...
    @property
    def matrix(self) -> Array: ...
    def forward_and_log_det(self, x: Array) -> tuple[Array, Array]: ...
    def same_as(self, other: base.Bijector) -> bool: ...
