from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.bijectors import gumbel_cdf as gumbel_cdf, tanh as tanh

tfb: Incomplete
RTOL: float

class GumbelCDFTest(parameterized.TestCase):
    seed: Incomplete
    def setUp(self) -> None: ...
    def test_properties(self) -> None: ...
    def test_forward_shapes(self, x_shape) -> None: ...
    def test_inverse_shapes(self, y_shape) -> None: ...
    def test_forward(self) -> None: ...
    def test_forward_log_det_jacobian(self) -> None: ...
    def test_forward_and_log_det(self) -> None: ...
    def test_inverse(self) -> None: ...
    def test_inverse_log_det_jacobian(self) -> None: ...
    def test_inverse_and_log_det(self) -> None: ...
    def test_stability(self) -> None: ...
    def test_jittable(self): ...
    def test_same_as(self) -> None: ...
