from absl.testing import parameterized
from distrax._src.bijectors import scalar_affine as scalar_affine

class ScalarAffineTest(parameterized.TestCase):
    def test_properties(self) -> None: ...
    def test_raises_if_both_scale_and_log_scale_are_specified(self) -> None: ...
    def test_shapes_are_correct(self) -> None: ...
    def test_forward_methods_are_correct(self) -> None: ...
    def test_inverse_methods_are_correct(self) -> None: ...
    def test_composite_methods_are_consistent(self) -> None: ...
    def test_batched_parameters(
        self, scale_batch_shape, shift_batch_shape, input_batch_shape
    ) -> None: ...
    def test_jittable(self): ...
