from _typeshed import Incomplete
from distrax._src.bijectors import bijector as base

Array: Incomplete
Numeric = Array | float

class ScalarAffine(base.Bijector):
    def __init__(
        self,
        shift: Numeric,
        scale: Numeric | None = None,
        log_scale: Numeric | None = None,
    ) -> None: ...
    @property
    def shift(self) -> Numeric: ...
    @property
    def log_scale(self) -> Numeric: ...
    @property
    def scale(self) -> Numeric: ...
    def forward(self, x: Array) -> Array: ...
    def forward_log_det_jacobian(self, x: Array) -> Array: ...
    def forward_and_log_det(self, x: Array) -> tuple[Array, Array]: ...
    def inverse(self, y: Array) -> Array: ...
    def inverse_log_det_jacobian(self, y: Array) -> Array: ...
    def inverse_and_log_det(self, y: Array) -> tuple[Array, Array]: ...
    def same_as(self, other: base.Bijector) -> bool: ...
