from absl.testing import parameterized
from distrax._src.bijectors.shift import Shift as Shift
from distrax._src.bijectors.tanh import Tanh as Tanh

class ShiftTest(parameterized.TestCase):
    def test_jacobian_is_constant_property(self) -> None: ...
    def test_properties(self) -> None: ...
    def test_forward_methods(self, batch_shape, param_shape) -> None: ...
    def test_inverse_methods(self, batch_shape, param_shape) -> None: ...
    def test_jittable(self): ...
    def test_same_as_itself(self) -> None: ...
    def test_not_same_as_others(self) -> None: ...
