from _typeshed import Incomplete
from distrax._src.bijectors import bijector as base

Array: Incomplete

class Sigmoid(base.Bijector):
    def __init__(self) -> None: ...
    def forward_log_det_jacobian(self, x: Array) -> Array: ...
    def forward_and_log_det(self, x: Array) -> tuple[Array, Array]: ...
    def inverse_and_log_det(self, y: Array) -> tuple[Array, Array]: ...
    def same_as(self, other: base.Bijector) -> bool: ...
