from absl.testing import parameterized
from distrax._src.bijectors.tanh import Tanh as Tanh
from distrax._src.bijectors.unconstrained_affine import (
    UnconstrainedAffine as UnconstrainedAffine,
)

class UnconstrainedAffineTest(parameterized.TestCase):
    def test_properties(self) -> None: ...
    def test_invalid_properties(self, bij_params) -> None: ...
    def test_batched_parameters(
        self, matrix_batch_shape, bias_batch_shape, input_batch_shape
    ) -> None: ...
    def test_identity_initialization(self, batch_shape, param_shape) -> None: ...
    def test_inverse_methods(self, batch_shape, param_shape) -> None: ...
    def test_forward_jacobian_det(self) -> None: ...
    def test_inverse_jacobian_det(self) -> None: ...
    def test_raises_on_invalid_input_shape(self) -> None: ...
    def test_jittable(self): ...
    def test_same_as_itself(self) -> None: ...
    def test_not_same_as_others(self) -> None: ...
