name: docs

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write

jobs:
  build-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install .[dev] mkdocs mkdocstrings[python]
      - run: mkdocs build
      - name: Commit documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add site
          git commit -m "Build documentation" || echo "No changes to commit"
          git push
