name: long tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  longrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install .[dev]
      - run: pytest -m longrun
