from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.utils import jittable as jittable

class DummyJittable(jittable.Jittable):
    name: str
    data: Incomplete
    def __init__(self, params) -> None: ...

class JittableTest(parameterized.TestCase):
    def test_jittable(self): ...
    def test_vmappable(self): ...
    def test_traceable(self): ...
    def test_different_jittables_to_compiled_function(self): ...
    def test_modifying_object_data_does_not_leak_tracers(self): ...
    def test_metadata_modification_statements_are_removed_by_compilation(self): ...
