from absl.testing import absltest
from distrax._src.utils import math as math

class MathTest(absltest.TestCase):
    def test_multiply_no_nan(self) -> None: ...
    def test_multiply_no_nan_grads(self): ...
    def test_power_no_nan(self) -> None: ...
    def test_power_no_nan_grads(self): ...
    def test_normalize_probs(self) -> None: ...
    def test_normalize_logits(self) -> None: ...
    def test_sum_last(self) -> None: ...
    def test_log_expbig_minus_expsmall(self) -> None: ...
    def test_log_beta(self) -> None: ...
    def test_log_beta_bivariate(self) -> None: ...
    def test_log_beta_multivariate(self) -> None: ...
