from absl.testing import absltest
from distrax._src.distributions import mvn_diag as mvn_diag, normal as normal
from distrax._src.utils import monte_carlo as monte_carlo

class McTest(absltest.TestCase):
    def test_estimate_kl_with_dice(self) -> None: ...
    def test_estimate_continuous_kl_with_dice(self) -> None: ...
    def test_estimate_continuous_kl_with_reparameterized(self) -> None: ...
    def test_estimate_mode(self) -> None: ...
