from _typeshed import Incomplete
from absl.testing import parameterized
from distrax._src.utils import transformations as transformations

tfd: Incomplete
tfb: Incomplete
RTOL: float

class TransformationsTest(parameterized.TestCase):
    seed: Incomplete
    def setUp(self) -> None: ...
    def test_inversion(self, forward, inverse, x) -> None: ...
    def test_inverting_jitted_function(self, forward, inverse, x) -> None: ...
    def test_log_det_scalar(self, forward, tfb_bijector, x) -> None: ...
    def test_is_constant_jacobian(self, fn, is_constant, x: float = 0.0) -> None: ...
