from _typeshed import Incomplete

def register_inverse(
    primitive, inverse_left, inverse_right: Incomplete | None = None
) -> None: ...
def inv(fun): ...
def is_constant_jacobian(fn, x: float = 0.0): ...
def log_det_scalar(fn): ...
